config/routes.rb
Rails.application.routes.draw do
  
  resources :charges

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'static_pages#home'
  get '/profil', to: 'static_pages#profil'
  
  get '/carts/new', to: 'carts#new'
  
  get '/carts/edit/:id_item_to_del', to: 'carts#edit'
  get '/carts/show/', to: 'carts#show'
  get '/carts/pay/:money', to: 'carts#pay', as: 'payment' # -> /carts/pay/payment
  # get '/users/:un_nom_de_variable', to: 'users#méthode', as: 'ton_nom_de_path_trop_cool'

  get '/item/:id_item_detail', to: 'items#show'
  get '/item/add/:id_item_to_add', to: 'items#add'

  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	
	# has_and_belongs_to_many :items

	validates :user_id, uniqueness: true

	has_many :stores
	has_many :carts, through: :stores
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, uniqueness: true

	# has_and_belongs_to_many :carts

	has_many :stores
	has_many :carts, through: :stores
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord

	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	belongs_to :cart, required: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def show 

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def edit
    @id_item_to_del = params[:id_item_to_del]

    @num_cart_user = Cart.find_by(user_id: current_user.id).id
    @tab = Store.where(cart_id: @num_cart_user)

    @tab.each_with_index do |i, nb|
      if "#{nb+1}" == @id_item_to_del
        i.destroy
      end
    end

    redirect_to "/carts/show"
  end


  def new
  end


  def show
    if user_signed_in?
      @id_user = current_user.id
      @cart_id = Cart.find_by(user_id: @id_user).id

    	@name_user = current_user.email
      num_cart = Cart.find_by(user_id: @id_user)
      @cart = Store.where(cart_id: num_cart.id)

      @prix_total_panier_float = 0.0
      @item_prix_float = 0.0
      @cart.each do |i|
        @item_prix_float = Item.find(i.item_id).price.to_i+ "0.#{Item.find(i.item_id).price.split(",")[1]}".to_f
        @prix_total_panier_float += @item_prix_float
      end

      @prix_total_panier_float = @prix_total_panier_float.round(2)
      @prix_total_panier_string = "#{@prix_total_panier_float.to_i},#{@prix_total_panier_float.to_s.split(".")[1]}"

    end
  end

  def pay
    @to_pay_string = params[:money]
    @to_pay_float = "#{@to_pay_string.to_i}.#{@to_pay_string.split(",")[1]}".to_f

    if user_signed_in?
      Order.create(user_id: current_user.id, prix_total: @to_pay_string)

    puts "===================================="
    puts "Je suis le controler pay"
    UserMailer.contact.delivery_now
    puts "var:" + @var.to_s
    puts "===================================="

      # vide le panier

      Store.where(cart_id: Cart.find_by(user_id: current_user.id)).each do |i|
        i.destroy
      end

    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def create
  # Amount in CENTS / CENTIMES
  @prix_total = Order.where(user_id: current_user.id).last.prix_total.to_i + "0.#{Order.where(user_id: current_user.id).last.prix_total.split(",")[1]}".to_f
  @amount = (@prix_total*100).to_i

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'carte de chatons',
    :currency    => 'EUR'
  )

  redirect_to :root

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to :root
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
  end

  def show
  	@id_to_send = params[:id_item_detail]
  	@id_item_detail = params[:id_item_detail]
  	@item = Item.find(params[:id_item_detail])
  end

  def add
  	@id_item = params[:id_item_to_add].to_i
  	@item = Item.find(@id_item)

  	mon_ajout = Store.new(cart_id: Cart.find_by(user_id: current_user.id).id, item_id: @item.id)
  	mon_ajout.save
  	# redirect_to "/item/#{@id_item}"
  	redirect_to "/"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  	@all = Item.all

  	if user_signed_in?
  		mon_cart = Cart.create(user_id: current_user.id)

  	end
  end

  def profil
      @id_user = current_user.id

      if Order.find_by(user_id: @id_user) != nil
        @order_id = Order.find_by(user_id: @id_user).id
        @order = Order.where(user_id: current_user.id)
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/edit.html.erb
<br><br>

<h1>
	Supprimer l'article N°<%= @id_item_to_del %> du panier
</h1>

	<br><br>
	User : <%= User.find(current_user.id).email %>

	<br><br>

	<% @tab.each_with_index do |i, nb| %>
		<ul>
			tour n°<%= nb+1 %><br>
			item to del is n°<%= @id_item_to_del %>
			
			<% if "#{nb+1}" == @id_item_to_del %>
				<h3> A supprimer dans le panier : </h3>
				<li>
					<%= nb+1 %>) <%= Item.find(i.item_id).title %>
					<%= i.destroy %>
				</li>
			<% end %>
		</ul>
	<% end %>

	<br><br>
	

app/views/carts/pay.html.erb
<br><br>

<% if user_signed_in? %>
	<!-- <h1> Params : '<%= @to_pay_string %>'€ </h1>
	<h1> ParamsClass : '<%= @to_pay_string.class %>' </h1>
	<br><br>

	<h1> Params Converti: <%= @to_pay_float %>€ </h1>
	<h1> ParamsClass : <%= @to_pay_float.class %> </h1> -->

	<br><br>
	<h1>Bonjour <%= current_user.email %>, </h1>
	<h1>Vous devez payez <%= @to_pay_float %>€ </h1>

	<%= form_tag charges_path do %>
		<article>
			<% if flash[:error].present? %>
				<div id="error_explanation">
					<p><%= flash[:error] %></p>
				</div>
			<% end %>
		<label class="amount">
		<span>Amount: <%= @to_pay_float %></span>
		</label>
		</article>

		<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			    data-description="carte de chaton"
			    data-amount= <%= @to_pay_float * 100 %>
			    data-locale="auto"></script>
	<% end %>

<% else %>
	<div class="alert alert-danger" role="alert" style="text-align: center;">
		<br>
		Connecte-toi pour passez une commande!
		<br>
	</div>

<% end %>

app/views/carts/show.html.erb
<div class="wrapper">
	<% if !user_signed_in? %>
		<br>
		<div class="alert alert-danger" role="alert" style="text-align: center;">
			Connecte-toi pour voir le panier !
		</div>
	<% else %>
		<div class="container">
			<h3>Ton panier :</h3>
			<div class="info-cart">
				<span>Email :</span> <%= @name_user %><br>
				<span>ID:</span> <%= @id_user %><br>
				<span>Numéro du panier : <%= @cart_id %></span> 
			</div>
		
		<div class="container">
			<table class="table">
				<thead>
					<tr>
					<th scope="col">#</th>
					<th scope="col">Article</th>
					<th scope="col">Prix</th>
					<th scope="col"> </th>
					</tr>
				</thead>
				<tbody>
					<% @cart.each_with_index do |item, i| %>
					<tr>
					<th scope="row"><%= i+1 %></th>
					<td><%= Item.find(item.item_id).title %></td>
					<td><%= Item.find(item.item_id).price %> </td>
					<td><a class="btn-suppr" href="/carts/edit/<%= i+1 %>" >Supprimer</a></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

	<% end %>

	<h2 class="total"><b>Total :</b> <%= @prix_total_panier_float %> € </h2>

	<a class="btn btn-success" href="<%= payment_path( @prix_total_panier_string ) %>">Passez commande</a>

</body>

</html>

app/views/items/add.html.erb
<br>

<% if user_signed_in? %>
	<h1> User id : <%= current_user.id %> -> <%= current_user.email %> </h1>
<% end %>
<h2> Information about Item N°<%= @id_item %> </h2>

<strong>Title : </strong> <%= @item.title %>
<br>
<strong>Prix : </strong> <%= @item.price %>

app/views/items/show.html.erb
<div class="wrapper">
	<h1><%= @item.title %></h1>
		<div class="container">
			<div class="item-image">
				<%= image_tag("/#{@item.image_url}", size: "600x400") %>
				<span class="desc-text"><b>Description :</b> <%= @item.description %></span> 
			</div>

			<div class="columns">
				<ul class="price">
				<li class="header">Notre offre</li>
				<li class="grey"><%= @item.price %> €</li>
				<li>Papier glacé</li>
				<li>Format HD</li>
				<% if user_signed_in? %>
					<li class="button"><a href="/item/add/<%= @id_to_send %>" class="button">AJOUTER AU PANIER</a></li>
				<% else %>
					<li class="button"><a href="<%= new_user_registration_path %>" class="button">S'INSCRIRE</a></li>
				<% end %>
				</ul>
			</div>
		</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-white fixed-top">
  <div class="container">
    <a href=<%= root_path %> ><img class="logo" src="/cat-logo.jpg"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto" style="align-items: center;">
  <!-- Affichage des liens divers -->
      <li class="nav-item active">
        <a class="link-navbar" href=<%= root_path %> >Accueil
        <span class="sr-only">(current)</span>
        </a>
      </li>
  <!-- Affichage des boutons Log in/Log out etc... -->
    <% if user_signed_in? %> <!-- Connecté -->
      <li class="nav-item">
        <a class="link-navbar" href="/profil" style="margin-right: 10px;">Mon Profil</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-warning nav-link" href=<%= edit_user_registration_path %> >Edit</a>
        <%= link_to "Se déconnecter", destroy_user_session_path , method: :delete, class: "btn btn-danger nav-link" %>
      </li>
      <li class="nav-item">
        <a href="/carts/show"><img class="basket-icon" src="/basket-icon.png"></a>
      </li>
    <% else %> <!-- Pas connecté --> 
      <li class="nav-item">
        <a class="btn btn-info nav-link" href=<%= new_user_session_path %> >Se connecter</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-success nav-link" href=<%= new_user_registration_path %> >S'inscrire</a>
      </li>
  <% end %>
    </ul>
  </div> <!-- fin collapse --> 
  </div> <!-- fin container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">

    <!-- BOOTSTRAP CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/shop-homepage.css" rel="stylesheet">

    <title>ChatonPix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">ChatonPix</h1>

        </div>
        <!-- /.col-lg-3 -->

          <div class="row">

            <% @all.each_with_index do |item, i| %>   
            
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <%= image_tag("/#{item.image_url}", size: "358x205") %>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href= "/item/<%= i+1 %>" ><%= item.title %></a>
                  </h4>
                  <h5><%= "#{item.price}€" %></h5>
                  <p class="card-text"><%= item.description%></p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
                <% if user_signed_in? %>
                  <a class="btn btn-success" href="/item/add/<%= i+1 %>">Ajouter au panier</a>
                <% else %>
                  <a class="btn btn-success" href="<%= new_user_registration_path %>">S'incrire pour ajouter</a>
                <% end %>
              </div>
            </div>

           <% end %>

          </div>
      </div>
    </div>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

app/views/static_pages/profil.html.erb
<div class="wrapper">
<% if user_signed_in? %>
	
	<h1 class="profile-title">Mon profil</h1>
	
	<div class="container">
	<p><strong> Email: </strong> <%= User.find(current_user.id).email %></p>

	<p>
	<strong>Modifier mes informations : </strong>
	<a class="" href=<%= edit_user_registration_path %> >Editer</a> 
	</p>

	<% if current_user.admin == true %>
		<p class="link-admin">Dashboard admin : <a href="/admin">Accéder</a></p>
	<% end %>

	</div> <!-- fin container 1 -->

	<h2>Mes commandes :</h2>
	<div class="container">
			<table class="table">
				<thead>
					<tr>
					<th scope="col">Commande n°</th>
					<th scope="col">Prix total</th>
					</tr>
				</thead>
				<tbody>
					<% if Order.find_by(user_id: @id_user) != nil %>
						<% @order.each do |info| %>
							<tr>
							<td><%= info.id %></td>
							<td><%= info.prix_total %></td>
							</tr>
						<% end %>
					<% else %>
						<tr>
							<td><i>Tu n'as pas encore de commande.</i></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div> <!-- fin container 2 -->
	
	
<!-- Si utilisateur non connecté -->
<% else %>
	<div class="alert alert-danger" role="alert" style="text-align: center;">
		<br>
		Connecte-toi pour voir ton profil !
		<br>
	</div>
<% end %>
</div>